# Generated by Django 6.1.1 on 2026-10-03 08:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('good', 'Good'), ('neutral', 'Neutral'), ('tired', 'Tired'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('stressed', 'Stressed'), ('angry', 'Angry')], max_length=20)),
                ('score', models.PositiveSmallIntegerField(help_text='1 = very low, 5 = very good', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'mood entries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='mood_mooden_user_id_52c67e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='one_mood_entry_per_day')],
            },
        ),
    ]
