# Generated by Django 6.1.1 on 2026-10-03 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('grounding', 'Grounding'), ('breathing', 'Breathing'), ('relaxation', 'Relaxation')], max_length=20)),
                ('description', models.TextField()),
                ('steps', models.JSONField(default=list, help_text="List of {'title': ..., 'prompt': ...} dicts")),
                ('duration_minutes', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CBTReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.TextField(max_length=1500)),
                ('automatic_thought', models.TextField(max_length=1000)),
                ('evidence_for', models.TextField(max_length=1500)),
                ('evidence_against', models.TextField(max_length=1500)),
                ('balanced_thought', models.TextField(max_length=1000)),
                ('reflection', models.TextField(blank=True, max_length=1500)),
                ('ai_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='exercises_c_user_id_90b592_idx')],
            },
        ),
    ]
