"""Safety layer: runs BEFORE any LLM call.

Approach (deliberately simple and transparent):
* regular expressions for explicit self-harm / suicide / immediate-danger language
* a short negation check so "I would never hurt myself" is not treated as a crisis
* two levels: HIGH (skip the LLM, give a calm fixed crisis response) and
  ELEVATED (continue, but tell the LLM to be extra careful)

This is a keyword-based screen, not a clinical tool. It errs on the side of caution
and should be improved/reviewed before any real deployment.
"""
import logging
import re
from dataclasses import dataclass, field

from django.conf import settings

logger = logging.getLogger(__name__)

NONE = "none"
ELEVATED = "elevated"
HIGH = "high"

# --- patterns (case-insensitive) ---------------------------------------------------
HIGH_RISK_PATTERNS = [
    r"\bkill(ing)? myself\b",
    r"\bend(ing)? (my|it all|my own) life\b",
    r"\bend it all\b",
    r"\bsuicid(e|al)\b",
    r"\b(want|wanna|going|plan(ning)?|ready|thinking of|thinking about) (to )?(die|disappear forever)\b",
    r"\bwant(ed)? to be dead\b",
    r"\bdon'?t want to (live|be alive|be here anymore|wake up)\b",
    r"\bno reason to (live|go on)\b",
    r"\bbetter off (dead|without me)\b",
    r"\b(hurt|harm|cut|injure|punish)(ing)? myself\b",
    r"\bself[- ]?harm\b",
    r"\boverdos(e|ing)\b",
    r"\btake all (my|the) (pills|tablets)\b",
    r"\bhang myself\b",
    r"\bjump (off|from)\b.*\b(bridge|building|roof|cliff)\b",
    r"\b(have|got) a plan to (die|end)\b",
    r"\bkill (him|her|them|someone|somebody)\b",
    r"\bhurt (someone|somebody|other people)\b",
    r"\b(i am|i'm|im) in danger\b",
    r"\bsomeone is (hurting|abusing|attacking) me\b",
    r"\b(life|it) isn'?t worth living\b",
]

ELEVATED_PATTERNS = [
    r"\bhopeless\b",
    r"\bno point (in|to) (anything|living|trying|going on)\b",
    r"\bcan'?t (go on|take (it|this) anymore|do this anymore)\b",
    r"\bgive up on (life|everything)\b",
    r"\bworthless\b",
    r"\bhate myself\b",
    r"\bnobody (cares|would (notice|miss me))\b",
    r"\bpanic attack\b",
    r"\bcan'?t breathe\b",
    r"\bfeel (so )?(empty|numb) (all the time|inside)\b",
    r"\bburden (to|on) (everyone|everybody|my family)\b",
]

# Words shortly BEFORE a match that flip its meaning (e.g. "I would never kill myself").
NEGATIONS = r"(never|not|no longer|don'?t|would not|wouldn'?t|won'?t|am not|i'?m not|isn'?t|nor)"
# Patterns where a preceding negation means the opposite (not for e.g. "don't want to live").
NEGATABLE_EXCEPTIONS = (r"\bdon'?t want to", r"\bno reason to", r"\bisn'?t worth", r"\bbetter off")

_HIGH = [re.compile(p, re.IGNORECASE) for p in HIGH_RISK_PATTERNS]
_ELEVATED = [re.compile(p, re.IGNORECASE) for p in ELEVATED_PATTERNS]
_NEGATION_RE = re.compile(NEGATIONS + r"\W+(\w+\W+){0,3}$", re.IGNORECASE)


@dataclass
class SafetyResult:
    level: str = NONE
    matched: list = field(default_factory=list)

    @property
    def is_high_risk(self):
        return self.level == HIGH

    @property
    def is_elevated(self):
        return self.level == ELEVATED


def _is_negated(text, match):
    """True if a negation word appears just before the matched phrase."""
    if any(re.search(p, match.group(0), re.IGNORECASE) for p in NEGATABLE_EXCEPTIONS):
        return False
    window = text[max(0, match.start() - 30): match.start()]
    return bool(_NEGATION_RE.search(window))


def _find(patterns, text):
    hits = []
    for pattern in patterns:
        for match in pattern.finditer(text):
            if not _is_negated(text, match):
                hits.append(match.group(0).lower())
    return hits


def assess_message(text):
    """Classify a user message into none / elevated / high risk."""
    text = (text or "").strip()
    if not text:
        return SafetyResult()
    high_hits = _find(_HIGH, text)
    if high_hits:
        logger.warning("Safety: HIGH risk language detected (%d match(es)).", len(high_hits))
        return SafetyResult(HIGH, high_hits)
    elevated_hits = _find(_ELEVATED, text)
    if elevated_hits:
        logger.info("Safety: elevated distress language detected.")
        return SafetyResult(ELEVATED, elevated_hits)
    return SafetyResult()


def get_crisis_resources():
    """Resources come from settings.CRISIS_RESOURCES so they can be localised."""
    return list(getattr(settings, "CRISIS_RESOURCES", []))


def build_crisis_response():
    """Short, calm, fixed response. Never generated by the LLM, so it is always safe."""
    lines = [
        "I'm really sorry you're going through something this painful, and I'm glad you told me. "
        "Your safety matters most right now.",
        "",
        "If you might act on these thoughts or you're in immediate danger, please contact "
        "your local emergency services now. If you can, reach out to someone you trust and "
        "ask them to stay with you.",
        "",
    ]
    for resource in get_crisis_resources():
        lines.append(f"• **{resource.get('name', '')}** – {resource.get('contact', '')}")
    lines += [
        "",
        "A qualified mental-health professional or a crisis service can give you the support you deserve. "
        "I'm an AI wellness companion, so I can't provide emergency help, but I'm here to listen. "
        "Are you somewhere safe right now?",
    ]
    return "\n".join(lines)


# --- output screening --------------------------------------------------------------
UNSAFE_OUTPUT_PATTERNS = [
    re.compile(p, re.IGNORECASE)
    for p in (
        r"\byou (have|are suffering from|are diagnosed with|likely have|probably have) (clinical )?(depression|anxiety disorder|bipolar|ptsd|adhd|ocd|schizophrenia|a mental illness)\b",
        r"\byou(?:'re| are) (clinically )?depressed\b",
        r"\bI (diagnose|can diagnose)\b",
        r"\b(take|try|increase|stop|start) (\d+\s?)?(mg|milligrams?)\b",
        r"\b\d+\s?mg\b",
        r"\b(antidepressants?|ssri|benzodiazepines?|xanax|prozac|sertraline|valium)\b.*\b(take|dose|dosage|prescribe)\b",
        r"\bI(?:'m| am) (a|your) (human|therapist|psychologist|psychiatrist|doctor)\b",
    )
]


def is_output_safe(reply_text):
    """Return False if the model's reply contains diagnosis/medication/human-claim wording."""
    for pattern in UNSAFE_OUTPUT_PATTERNS:
        if pattern.search(reply_text or ""):
            logger.warning("Safety: unsafe LLM output blocked (pattern %s).", pattern.pattern[:40])
            return False
    return True
